{% set name = "glue-plotly" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 38a98acb940b985fbb48a9cbdbf50e67123ec582d0bd0b39c1a5afdeb5a6285f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - glue-core >=1.13.1
    - plotly
    - chart-studio

test:
  imports:
    - glue_plotly
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/glue-viz/glue-plotly
  summary: Experimental plot.ly exporters for glue
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - astrofrog
